/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.struts.hibernate.app;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
